repos:
-   repo: https://github.com/pycqa/flake8
    rev: 'c8d1be6'  # pick a git hash / tag to point to
    hooks:
    -   id: flake8
    additional_dependencies: [flake8-docstrings, flake8-annotations, flake8-bandit]
